notifications:
  email:
    - bart@mynameisbart.com

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

matrix:
  allow_failures:
    - php: 7

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin

script:
  # Update Composer.
  - composer self-update
  - cd $TRAVIS_BUILD_DIR
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - git branch build-$TRAVIS_COMMIT $TRAVIS_COMMIT
  - git branch -a

  # Download Drupal core.
  - cd $TRAVIS_BUILD_DIR/..
  - composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction --no-install

  # Add Currency to Drupal core.
  - cd $TRAVIS_BUILD_DIR/../drupal
  - $TRAVIS_BUILD_DIR/bin/add-vcs-repository-to-composer-json $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../drupal/composer.json
  - composer require -vvv drupal/core:8.0.x-dev
  - composer require -vvv drupal/currency:dev-build-$TRAVIS_COMMIT@dev --prefer-source -n
  - cat composer.json

  # Run PHPUnit tests.
  - cd $TRAVIS_BUILD_DIR/../drupal/web/core
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c ../modules/contrib/currency/phpunit.xml.dist --bootstrap ./tests/bootstrap.php --verbose --debug --coverage-clover ./build/logs/clover.xml || exit 1
  - php ./vendor/bin/coveralls -vvv -c ../modules/contrib/currency/.coveralls.yml

  # Fix run-tests.sh's output. See https://www.drupal.org/node/2189345.
  - cd $TRAVIS_BUILD_DIR/../drupal/web
  - curl https://www.drupal.org/files/issues/2189345-61.patch | git apply

  # Install Apache.
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # Install Drupal
  - cd $TRAVIS_BUILD_DIR/../drupal/web
  - ../vendor/drush/drush/drush si --db-url=mysql://root:@127.0.0.1/drupal --account-pass=admin -y
