notifications:
  email:
    - bart@mynameisbart.com

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

matrix:
  allow_failures:
    - php: 7

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin

install:
  # Install Drush.
  - composer global require --no-interaction --prefer-dist drush/drush:dev-master

  # Install Apache.
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi

before_script:
  # Download Drupal core.
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --branch 8.0.x --depth 1 http://git.drupal.org/project/drupal.git

  # Fix run-tests.sh's output. See https://www.drupal.org/node/2189345.
  - cd drupal
  - curl https://www.drupal.org/files/issues/2189345-61.patch | git apply

  # Copy Currency into Drupal core.
  - cp -Rv $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../drupal/modules/

  # Enable Currency and let Composer Manager install Composer dependencies.
  - cd $TRAVIS_BUILD_DIR/../drupal
  - drush en currency -y

script:
  # Run PHPUnit tests and submit code coverage statistics.
  - cd $TRAVIS_BUILD_DIR/../drupal/modules/currency
  - mkdir -p build/logs
  - ../../core/vendor/bin/phpunit -c ./phpunit.xml.dist --bootstrap ../../core/tests/bootstrap.php --verbose --debug --coverage-clover ./build/logs/clover.xml || exit 1
  - php ./vendor/bin/coveralls -v -c ./.coveralls.yml
