notifications:
  email:
    - bart@mynameisbart.com

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

matrix:
  allow_failures:
    - php: 7

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin

script:
  # Download Drupal core.
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --branch 8.0.x --depth 1 http://git.drupal.org/project/drupal.git

  # Add Currency to Drupal core.
  - cd $TRAVIS_BUILD_DIR/../drupal
  - ./modules/currency/bin/add-vcs-repository-to-composer-json $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../drupal/core/composer.json
  - cd core
  - composer require drupal/currency:dev-master --prefer-source -n -vvv

  # Run PHPUnit tests.
  - cd $TRAVIS_BUILD_DIR/../drupal/core
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c ../modules/currency/phpunit.xml.dist --bootstrap ./tests/bootstrap.php --verbose --debug --coverage-clover ./build/logs/clover.xml || exit 1
  - php ./vendor/bin/coveralls -vvv -c ../modules/currency/.coveralls.yml

  # Fix run-tests.sh's output. See https://www.drupal.org/node/2189345.
  - cd $TRAVIS_BUILD_DIR/../drupal
  - curl https://www.drupal.org/files/issues/2189345-61.patch | git apply

  # Install Drush.
  - composer global require drush/drush:dev-master --prefer-source -n -vvv

  # Install Apache.
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # Install Drupal
  - cd $TRAVIS_BUILD_DIR/../drupal
  - drush si --db-url=mysql://root:@127.0.0.1/drupal --account-pass=admin -y
