currency.currency.*:
  label: Currency
  type: mapping
  mapping:
    alternativeSigns:
      type: sequence
      label: Alternative signs
      sequence:
        - type: string
          label: Alternative sign
    exchangeRates:
      type: sequence
      label: Historical exchange reates
      sequence:
        - type: string
          label: Historical exchange rates
    currencyCode:
      label: Currency code
      type: string
    currencyNumber:
      label: Currency number
      type: string
    label:
      label: Label
      type: label
    roundingStep:
      label: Rounding step
      type: float
    sign:
      label: Currency sign
      type: string
    subunits:
      label: Number of subunits
      type: integer
    status:
      label: Status
      type: boolean
    usages:
      type: sequence
      label: Usages
      sequence:
        - type: mapping
          label: Usage
          mapping:
            countryCode:
              label: Country code
              type: string
            start:
              label: Start date
              type: string
            end:
              label: End date
              type: string
    uuid:
      label: Universally Unique ID
      type: string

currency.currency_locale.*:
  label: Currency locale
  type: mapping
  mapping:
    decimalSeparator:
      label: Decimal separator
      type: string
    groupingSeparator:
      label: Grouping separator
      type: string
    locale:
      label: Locale
      type: string
    pattern:
      label: Unicode CLDR number pattern
      type: string
    uuid:
      label: Universally Unique ID
      type: string

currency.amount_formatting:
  label: Currency amount formatting
  type: mapping
  mapping:
    plugin_id:
      label: Plugin ID
      type: string

currency.exchange_rate_provider:
  label: Currency exchange rate provider
  type: mapping
  mapping:
    plugins:
      type: sequence
      sequence:
        - type: mapping
          label: Plugin
          mapping:
            plugin_id:
              label: Plugin ID
              type: string
            status:
              label: Status
              type: boolean

currency.exchange_rate_provider.fixed_rates:
  label: Fixed currency exchange rates
  type: mapping
  mapping:
    rates:
      type: sequence
      sequence:
        - type: mapping
          label: Plugin
          mapping:
            currency_code_from:
              label: Source currency code
              type: string
            currency_code_to:
              label: Destination currency code
              type: string
            rate:
              label: Exchange rate
              type: string
